# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51227a7c687672958abe62ba29fc8a0f"
application_url = "https://deliveright-598053309572.us-central1.run.app"
embedded = true
name = "deliveright-white-glove"
handle = "deliveright-white-glove-3"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_locations,read_orders,read_products,read_shipping,write_fulfillments,write_orders,write_shipping,read_inventory,read_markets_home"

[auth]
redirect_urls = [
  "https://deliveright-598053309572.us-central1.run.app/auth/callback",
  "https://deliveright-598053309572.us-central1.run.app/auth/shopify/callback",
  "https://deliveright-598053309572.us-central1.run.app/api/auth/callback"
]

[pos]
embedded = false
